# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  thymeleaf.cache: false
  main.show-banner: false
  session:
    store-type: jdbc
  datasource:
    url: jdbc:postgresql://localhost:5432/company
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  web:
    cors:
    enabled: true
#  autoconfigure:
#    exclude:
#    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8060

